version: "3"
services:
  neko:
    image: "vaibhavkarade/vitualbrowser:latest"
    restart: "unless-stopped"
    shm_size: "2gb"
    ports:
      - "8090:8090"
      - "52000-52100:52000-52100/udp"
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: neko
      NEKO_PASSWORD_ADMIN: admin
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1
